kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: preston-battin-website-frontend-production
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: preston-battin-website
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/preston-battin-website/github.com/pbattin/gcp-ci-cd
        resources:
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: production
        ports:
        - name: backend
          containerPort: 8080
